$(`<a id="عاصم" href=""><i class="fa fa-refresh fa-spin fa-3x fa-fw" aria-hidden="true"></i></a><img id="asim70"src=""style="width:100%"><a id="asim27"target="_blank"type="a"rel="nofollow"title=""href=""class="label-primary"></a></div></div><center>`).insertBefore(".nav-tabs"),$(".nav-tabs").addClass("fl").css("width","100%"),
$(`<center><div id="asim1">
<a id="asim7"rel="dofollow" title="القوانين" href=""style="border-radius: 0 4px 0 0; border-right: 2px solid#f7d322;"class="fl mini  fa fa-bullhorn btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="الاشتراكات" href=""style="border-right: 1px solid#fff;"class="fl mini  fa fa-star-half-o btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="راديو" href=""style="border-right: 1px solid#fff;"class="fl mini  fa fa-volume-up btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="زخرفة اسماء" href=""style="border-right: 1px solid#fff;"class="fl mini  fa fa-fire btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="اتصل بنا" href=""style="border-right: 1px solid#fff;"class="fl mini fa fa-paper-plane btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="قوانين السوابر" href=""style="border-right: 1px solid#fff;"class="fl mini fa fa-exclamation-triangle btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="تطبيق الشات" href=""style="border-right: 1px solid#fff;"class="fl mini fa fa-android btn btn-primary" target="_blank"></a>
<a id="asim7"rel="dofollow" title="اختصارات الشات" href=""style="border-radius: 6px 0 0 0; border-left: 3px solid#f7d322; border-right: 1px solid#ffffff;"class="fl mini fa fa-tencent-weibo btn btn-primary" target="_blank"></a>
</div></div><center>`).insertBefore('div#tlogins .lonline.light.break');
$(`<center><div><marquee direction="right" id="as43" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="3"> &nbsp;أهلا وسهلا بكم في شات <font color="#595757" class="asim12">نجمه الحب   </font> ● · ‫أفضل سوبر لهذا الأسبوع · ● <font class="asim11" color="#727A54">&nbsp; قـــريــــبـــآ &nbsp;</font> ● · ‫أفضل زائر لهذا الأسبوع · ● <font class="asim11" color="#ff9900">&nbsp;قـــريــــبـــآ&nbsp;</font> ● · ‫أفضل زائرة لهذا الأسبوع · ● <font class="asim11" color="#ff00ff">&nbsp; قـــريــــبـــآ &nbsp;</font> ● · مبدع الحائط لهذا الأسبوع · ● <font class="asim11" color="#BA5D82">&nbsp;  قـــريــــبـــآ &nbsp;</font> ● · مبدعة الحائط لهذا الأسبوع · ● <font class="asim11" color="#800000">&nbsp; قـــريــــبـــآ&nbsp;</font> ● · ‫أفضل تواجد لهذا الأسبوع · ● <font class="asim11" color="#B55B7F">&nbsp; قـــريــــبـــآ&nbsp;</font> ● · مع تمنياتنا للجميع بـ أطيب الاوقات&nbsp;</marquee></div><center>`).insertBefore('div#tlogins .lonline.light.break');
$(`<link rel="stylesheet" href="">`).insertBefore("body");
$('.ae.label.label-primary.fa.fa-gear')['html'](`${'⠀'}`);
$('label.ae.fa.label.label-primary.fa-commenting-o')['html'](`${'⠀'}`);
$('.ae.fa.label.label-primary.fa-users')['html'](`${'⠀'}`);
$('.hand.nosel.fl.uzr.border')['css']({ margin: '1px 0', borderRadius: '0px' }), $('.checkbox label')['html'](`${'<input id="stealth"type="checkbox"value=""><i class="fa fa-eye-slash"aria-hidden="true"style="margin-top: 3px"></i>'}`), $(`${'<a href="" target="_blank" id="as0" class="border">تطبيق الشات</a>'}`)['insertBefore']('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg'), $('.tc span[class="fa fl"]')['addClass']('fa-check');
var nopm = !0
    , nonot = !0;
$('#d0')['append'](`${'<label title="اذاعة  نجمه الحب"href="#"onclick="$(\'.pnhead\').text($(this).attr(\'title\'));hl($(this),\'primary\');setTimeout(function(){$(\'#mic\').scrollTop(0);},100);$(\'.dpnl\').show()"data-toggle="tab"data-target="#mic"class="asim ae fa label label-primary"><i class="fa fa-volume-up"aria-hidden="true"></i></label>'}`);
$('div#tlogins button.btn.btn-primary')['click'](function () { setTimeout(function () { refreshonline() }, 0) }), setInterval(function () { var _0x7332x3 = $('#dpnl');
    0 < _0x7332x3['length'] && _0x7332x3['remove']() }, 0), $('.dpnl')['append'](`${'<div id="mic"style="height: 100%;width:100%;"class="break light tab-pane border"><center></div><center></div>'}`), $('div#tlogins button.btn.btn-primary')['click'](function () { var _0x7332x4 = setInterval(function () { var _0x7332x5 = $('.pmsgc')['length']; if (_0x7332x5 > 0) { $(`${'<center><div></div><center><iframe frameborder="0"id="asim29"src="https://blog.iraqna.net/embed"></iframe><iframe frameborder="0" id="asim30" src=""></iframe></a>\x0D\x0A<a id="asim19"rel="dofollow" title="اتصل بالاذاعه" href="www.facebook.com"class="fl mini fa fa-tencent-weibo btn btn-primary" target="_blank"></a></div><center><div><textarea class="as2020" style="height:146px;overflow:hidden">\x0D\x0A⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ \x0D\x0A♔ ★  ║ لê  ♫ • ❥ ✿  ⌯ ✘ ،ٌ©®♡♰❰ ❱ ᵛ͢ᵎᵖ  ₎™ 🦅🌹💀☠️👑🌝✨💥🔥🍂☂ ❥ ‏˛⁽ ツ‏⠀ ᵀᴹ )"̯ء \x0D\x0Aڪـٰٖـٖ ـٰـٰٰـٰٰة ـٰٰٰٰ۪ٖ۫ـٰہـةﺔﺔ ،آ‘إْــِْـﮧٰٖـــــِْﮧٰٖــ ۽ۧ۽ۧ ــٰٰـٰـٰٰ ـٰٰـٰـٰٰـﮯ̷͡ـــ ـــٰۦـٰٖـٰـٰہٰٖءـٰـٰۦــ ــ♯ــٰـٰـٰۦـٰٰٰٖٖ\x0D\x0Aqતۦۦ᎗ۦۦ᎗බລܭɹ̇൧ٌᘓ۶ᒧხbl͠ \x0D\x0A</textarea><iframe frameborder="0" id="asim222" src="https://raw.githack.com/hussienail/Hos2/master/hos1.html" style="height:280px"></iframe></div>'}`)['appendTo']('#mic');
            clearInterval(_0x7332x4) } else { console['log'](_0x7332x5) } }, 2000) });
$('textarea#tbox')['bind']('contextmenu', function (_0x7332x6) { _0x7332x6['preventDefault']() }, false);
$('textarea#tbox')['on']('paste', function (_0x7332x6) { _0x7332x6['preventDefault']() });
$('div#l1 button.btn.btn-primary')['bind']('click', function () { alert('اهلا وسهلا بكم في شات نجمه الحب❤️ سجل عضوية تحصل على 5000 لايك وزخرفة :: طريقة التسجيل اضغط على خيار (تسجيل) اكتب (اكتب اسمك المستعار + كلمة المرور ) وبعدها اضغط دخول') });
$(`${'<style>.hand.corner{background-color:#000!important;border:2px solid #c12e2a!important;color:#f0ad4e;border-radius:0;text-align:center;border-style:solid;border-right:7px solid!important;border-left:7px solid!important;border-color:#2ea1ad;border-left-style:double!important;border-right-style:double!important}div.break.fl::before{content:" اخي الزائر اختي الزائرة اذا واجهت مشكله في دخول الشات يرجى مراسلتنا من صفحة اتصل بنا 📨 .. ";color:#0f0!important;font-family:\'jazeera\',FontAwesome;font-size:16px}.break.fl{text-align:center;padding:5px!important;font-family:\'jazeera\',FontAwesome;color:red;-webkit-animation:mymove .5s infinite;animation:mymove .5s infinite}</style>'}`)['insertBefore']('div#tlogins .lonline.light.break');
$(`<img tabindex="0" class="al120 fl " style="margin-left: -3px; padding:6px; width:35px;margin-top: -2px;" src="https://k.top4top.io/p_17044g8ns1.gif" data-original-title="" title="">`).insertAfter('img.fl.nosel.emobox');
$(".al120").click(function(){alert(" اللهم أحفـظ { آ‘إلـَعـِرآ‘إَْق } من كل بـلآء - تحيآتي للجميع ");});$('div#l2 button.btn.btn-primary')['bind']
$('div#l2 button.btn.btn-primary')['bind']('click', function () { alert (' اهلا  وسهلا بكم مجددآ ب شات نجمه الحب  ❤ ') });
$('div#l3 button.btn.btn-primary')['bind']('click', function () { alert (' ❤  ممنوع علي الجميع ذكر السياسات او سب الذات الالهية او ذكر  اسم مواقع وعدم مذايقة الزوار واتمنا من الجميع الالتزام ب القواعد والقوانين  الخاصة  ب شات ❤') });
